// Minimal translations for RebelMetrics.io - only for dynamic functionality
// Static text is now handled by separate HTML files per language
const translations = {
    en: {
        // Only keep translations for dynamic elements that are generated by JavaScript
        header: {
            by: "By"
        },
        nav: {
            services: "Services",
            features: "Features", 
            customers: "Customers",
            contact: "Contact"
        },
        hero: {
            cta: {
                quote: "Get Quote"
            }
        }
    },
    
    sv: {
        header: {
            by: "Av"
        },
        nav: {
            services: "Tjänster",
            features: "Funktioner",
            customers: "Kunder", 
            contact: "Kontakt"
        },
        hero: {
            cta: {
                quote: "Få offert"
            }
        }
    },
    
    de: {
        header: {
            by: "Von"
        },
        nav: {
            services: "Dienstleistungen",
            features: "Funktionen",
            customers: "Kunden",
            contact: "Kontakt"
        },
        hero: {
            cta: {
                quote: "Angebot anfordern"
            }
        }
    }
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = translations;
} 