#!/bin/bash

echo "🚀 Setting up RebelMetrics for Organization Root GitHub Pages"
echo ""

echo "📋 To deploy at https://digitalist-open-cloud.github.io/, you need to:"
echo ""
echo "1. Create a new repository named 'digitalist-open-cloud.github.io'"
echo "2. Copy all files from this repository to the new one"
echo "3. Enable GitHub Pages in the new repository"
echo ""

echo "🔗 Steps to follow:"
echo ""
echo "1. Go to: https://github.com/Digitalist-Open-Cloud"
echo "2. Click 'New repository'"
echo "3. Repository name: digitalist-open-cloud.github.io"
echo "4. Make it Public"
echo "5. Don't initialize with README (we'll copy files)"
echo "6. Click 'Create repository'"
echo ""

echo "📁 After creating the repository:"
echo ""
echo "1. Clone the new repository:"
echo "   git clone https://github.com/Digitalist-Open-Cloud/digitalist-open-cloud.github.io.git"
echo ""
echo "2. Copy all files from this directory to the new repository"
echo "3. Commit and push to the new repository"
echo "4. Enable GitHub Pages in Settings → Pages"
echo ""

echo "✅ Once completed, your site will be available at:"
echo "   https://digitalist-open-cloud.github.io/"
echo ""
echo "🌍 Language URLs:"
echo "   English: https://digitalist-open-cloud.github.io/"
echo "   Swedish: https://digitalist-open-cloud.github.io/sv/"
echo "   German:  https://digitalist-open-cloud.github.io/de/"
echo ""

echo "💡 Alternative: Keep current setup"
echo "   If you prefer to keep the current setup, use:"
echo "   https://digitalist-open-cloud.github.io/RebelSite/"
echo "" 